- name: Configure the Proxy device
  hosts: proxydevice
  become: yes
  tasks:
    - name: 1. Install the Firewall
      block:
      - name: Install firewall packages
        apt:
          name:
          - ufw
          - less  ## just useful to have
          state: present
          update_cache: yes

      - name: Set the Rules
        ## Certbot needs http
        shell: |
           ufw allow http
           ufw allow https
           ufw allow {{ ansible_port }}
           ufw allow from {{ hostvars["jupyterdevice"]["ansible_host"] }} to any port {{ proxy_port }}
           ufw default deny incoming

      - name: Enable UFW service
        systemd:
          name: ufw
          enabled: yes
          state: started

      - name: Start the UFW rules
        shell: yes | ufw enable

    - name: 2. Install Caddy
      block:
      - name: Install needed packages
        apt:
          name:
          - caddy
          state: present
          update_cache: yes

      - name: Create module dir
        file:
          path: /etc/caddy/conf.d
          state: directory

      - name: Configure caddy jupyter entry
        copy:
          dest: /etc/caddy/conf.d/jupyter
          content: |
             {{ hostvars["vars"]["domain_name"] }} {
                reverse_proxy localhost:{{ proxy_port }} {
                     header_up Host {host}
                     header_up X-Real-IP {remote}
                     header_up X-Forwarded-For {remote}
                     header_up X-Forwarded-Proto {scheme}
                 }
             }

      - name: Configure caddy conf
        lineinfile:
            path: /etc/caddy/Caddyfile
            state: present
            regexp: "^#?import /etc/caddy/conf.d/.*"
            line: "import /etc/caddy/conf.d/*"
            backup: no

      - name: Enable caddy service
        systemd:
          name: caddy
          enabled: yes
          state: started

    - name: 2.5 Install certificates
      block:
      - name: Install certbot
        apt:
          name: certbot
          state: present
          update_cache: yes

      - name: Set Caddy down
        systemd:
          name: caddy
          enabled: yes
          state: stopped

      - name: Configure certbot
        become: yes
        shell:
          cmd: |
            certbot renew \
                    -d {{ hostvars["vars"]["domain_name"] }} \
                    -m {{ hostvars["vars"]["certbot_admin_email"] }}

      - name: Set Caddy back up
        systemd:
          name: caddy
          enabled: yes
          state: started


    - name: 3. Setup the nginx proxy user
      block:
      - name: Make proxy user
        user:
          name: '{{ proxy_user }}'
          generate_ssh_key: true

      - name: Copy private key over to ansible device
        ## We use this to copy to the jupyter device
        fetch:
          src: '/home/{{ proxy_user }}/.ssh/id_rsa'
          dest: '/tmp/ssh_proxy_key'
          flat: true

      - name: Get the public key
        become: yes
        shell: 'cat /home/{{ proxy_user }}/.ssh/id_rsa.pub'
        register: proxy_ssh_key

      - name: Append key to authorized keys file
        lineinfile:
           path: /etc/ssh/authorized_keys
           regexp: '^{{ proxy_ssh_key.stdout | trim }}'
           line: '{{ proxy_ssh_key.stdout | trim }}'
