- name: Setup and Configure JupyterHub Pharma
  hosts: jupyter
  become: false
  vars:
    dir_pharma: /opt/jh-253/jupterhub-pharma
    metrics_repo: git+https://github.com/mtekman/jupyterhub@sysmon
    venv_dir: /opt/jh-253/venv
    proxy_port: 1234
    proxy_net: 127.0.0.1
    docker_ip: 172.17.0.1
  tasks:
  - name: Setup Install Directories
    become: yes
    cmd: |
      mkdir -p {{ dir_pharma }}
      mkdir -p {{ venv_dir }}
      chmod a+wrx {{ dir_pharma }}
      chmod a+wrx {{ venv_dir }}

  - name: Clone the repo
    shell: |
      ## Shallow clone the Pharma
      git clone --depth 1 https://gitlab.com/mtekman/jupyterhub-pharma253 \
        -b main {{ dir_pharma }}

  - name: Generate virtualenv for metrics repo and install it
    block:
    - name: Install pyvenv
      apt:
        name:
        - python3-venv
      state: present
      update_cache: yes

    - name: Install the Jupyterhub with Metrics into venv
      pip:
        virtualenv: '{{ venv_dir }}'
        virtualenv_python: python3
        name:
        - '{{ metrics_repo }}'
        - dockerspawner
        - psutil
        - configurable
        - http-proxy

  - name: Configure Jupyterhub Pharma
    ## We won't do the full configuration, just a working one.
    loop:
    ## Set Jupyter venv
    - { find: '^jupyter_venv = .*', set: 'jupyter_venv = "{{ venv_dir }}"', when: true }
    ## Set Admin users
    ## Set Read-only volumes
    ## Set Proxy
    - { find: '^server_type = .*', set: 'server_type = "proxy"', when: use_proxy}
    - { find: '^    c.JupyterHub.bind_url = .*',
         set: '^    c.JupyterHub.bind_url = "http://{{ proxy_net }}:{{ proxy_port }}"',
        when: true}
    ## Set Docker
    - { find: '^c.JupyterHub.hub_ip = .*',
          set: 'c.JupyterHub.hub_ip = "{{ docker_ip }}"', when: true}
    lineinfile:
      path: '{{ dir_pharma }}/jupyter_config.py'
      state: present
      regexp: "{{ item.find }}"
      line: "{{ item.set }}"
      when: "{{ item.when }}"
      backup: no

    