- name: Setup and Configure JupyterHub Pharma
  hosts: jupyter
  become: false
  vars:
    dir_pharma: /opt/jh-253/jupterhub-pharma
    metrics_repo: git+https://github.com/mtekman/jupyterhub@sysmon
    venv_dir: /opt/jh-253/venv
    proxy_port: 1234
    proxy_net: 127.0.0.1
    docker_ip: 172.17.0.1
    docker_cpuquota_perc: 7000
    docker_memhigh_gb: 230
    
  tasks:
  - name: Setup Install Directories
    become: yes
    cmd: |
      mkdir -p {{ dir_pharma }}
      mkdir -p {{ venv_dir }}
      chmod a+wrx {{ dir_pharma }}
      chmod a+wrx {{ venv_dir }}

  - name: Clone the repo
    shell: |
      ## Shallow clone the Pharma
      git clone --depth 1 https://gitlab.com/mtekman/jupyterhub-pharma253 \
        -b main {{ dir_pharma }}

  - name: Generate virtualenv for metrics repo and install it
    block:
    - name: Install pyvenv
      apt:
        name:
        - python3-venv
      state: present
      update_cache: yes

    - name: Install the Jupyterhub with Metrics into venv
      pip:
        virtualenv: '{{ venv_dir }}'
        virtualenv_python: python3
        name:
        - '{{ metrics_repo }}'
        - dockerspawner
        - psutil
        - configurable
        - http-proxy

  - name: Configure Jupyterhub Pharma
    ## We won't do the full configuration, just a working one.
    loop:
    ## Set Jupyter venv
    - { find: '^jupyter_venv = .*', set: 'jupyter_venv = "{{ venv_dir }}"', when: true }
    ## Set Admin users
    ## Set Read-only volumes
    ## Set Proxy
    - { find: '^server_type = .*', set: 'server_type = "proxy"', when: use_proxy}
    - { find: '^    c.JupyterHub.bind_url = .*',
         set: '^    c.JupyterHub.bind_url = "http://{{ proxy_net }}:{{ proxy_port }}"',
        when: true}
    ## Set Docker
    - { find: '^c.JupyterHub.hub_ip = .*',
          set: 'c.JupyterHub.hub_ip = "{{ docker_ip }}"', when: true}
    lineinfile:
      path: '{{ dir_pharma }}/jupyter_config.py'
      state: present
      regexp: "{{ item.find }}"
      line: "{{ item.set }}"
      when: "{{ item.when }}"
      backup: no

  - name: Configure the Docker Limits
    copy:
      src: /etc/systemd/system/docker_limit.slice
      content: |
        [Unit]
        Description=Slice that limits docker resources
        Before=slices.target

        [Slice]
        CPUAccounting=true
        CPUQuota={{ docker_cpuquota_perc }}%
        MemoryAccounting=true
        MemoryHigh={{ docker_memhigh_gb }}G

  - name: Configure the JupyterHub service file
    copy:
      src: /etc/system/systemd/system/jupyterhub.service
      content: |
        [Unit]
        Description=Jupyterhub Docker Service
        After=network.target
        Wants={{ proxy_service }} docker_limit.slice  ## weak dependency, jupyter still starts if proxy or docker limitter fails
        
        [Service]
        TODO: FINISH THIS
        Environment="PATH=/opt/jupyterhub/jupyterhub-pharma253/venv_jupyter_metrics/bin:%h/.local/bin:%h/bin:%h/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ExecStart=/opt/jupyterhub/jupyterhub-pharma253/venv_jupyter_metrics/bin/jupyterhub --config="/opt/jupyterhub/jupyterhub-pharma253/jupyterhub_config.py"
        WorkingDirectory=/opt/jupyterhub/jupyterhub-pharma253
        Restart=on-failure
        RestartSec=60
        User=root
        KillMode=process
        
        [Install]
        WantedBy=multi-user.target        
      